name: §l§8(§cก§6ะ§eบิ๊§aก§bว§dอ§cซี§8)§r
version: 999
main: system\Main
api: 3.0.0
author: Tanachotpat
description: §aเอาไปแจกต่อหรือขายต่อกุขอให้โครตพ่อโครตแม่มันชิบหายมีอันเป็นไป

commands:
 gmc:
  description:
 gms:
  description:
 gma:
  description:
 gmspec:
  description:
 mymoney:
  description:
 pay:
  description:
 setmoney:
  description:
 givemoney:
  description:
 setstar:
  description:
 paystar:
  description:
 setrgb:
  description:
 setlvl:
  description:
 givelvl:
  description:
 free:
  description:
 heal:
  description:
 farm:
  description:
 token:
  description:
 v:
  description:
 unv:
  description:
 shop:
  description: